### ISSUE TITLE
invalid command name "lipidbuilder_tk"

### ISSUE THREAD

**Issue by alkhalifas** [tlemmin/LipidBuilder#1]
I am trying to get this plugin installed, but I cannot seem to be able to do so.

I edited the .vmdrc file to include:
`lappend auto_path /Users/Username/plugins/LipidBuilder
vmd_install_extension lipidBuilder lipidbuilder_tk "Modeling/LipidBuild"`

Anytime I open VMD, i receive this warning:
`The lipidBuilder package could not be loaded:`

If I navigate to Modeling, and I click on LipidBuilder, I receive this error message:
`vmd > ERROR) Creation of window for 'lipidBuilder' failed (invalid command name "lipidbuilder_tk").`

Any thoughts on what I can do next?

Thanks!

**Comment by tlemmin** [comment]
Which version of VMD and operating system are you using?

Did you change the path (/Users/Username/plugins/) to the actual path on your computer?

**Comment by alkhalifas** [comment]
I am currently using VMD 1.9.2. And yes, the path is correct, but I removed my username before posting on here. It seems as though there is an issue with the `lipidbuilder_tk`. I tried googling this problem but nothing has come up.

Any thoughts?

**Comment by tlemmin** [comment]
There was a typo in the instructions for the .vmdrc. It should read:

lappend auto_path "your_path"/LipidBuilder
vmd_install_extension lipidbuilder lipidbuilder_tk "Modeling/LipidBuildLipidBuilder

I have add this to the README file.

**Comment by alkhalifas** [comment]
I just gave this a try and I am still getting the same error message. I think the issue is with the `lipidbuilder_tk`. No matter what the term after is changed to, the same error message appears.

**Comment by tlemmin** [comment]
Could you check if the package is loaded?
% lsearch [package names] lipidbuilder

**Comment by alkhalifas** [comment]
Im not very familiar with that (new to all of this). Do I just enter that exact command in the same directory (LipidBuilder)?

**Comment by tlemmin** [comment]
In VMD:
Extensions -> Tk Console
This will open a Tcl/Tk terminal. 
Type the command:
 lsearch [package names] lipidbuilder
If it returns -1, that means that lipidbuilder is not loaded.

**Comment by alkhalifas** [comment]
It did in fact return a -1. Any thoughts on what to do from here?

**Comment by tlemmin** [comment]
In the TkConsole, type:
puts $auto_path

This will list all the paths where VMD will search for a package. 
Check that there is no typo in LipidBuilder's path

**Comment by alkhalifas** [comment]
The path seems correct. The default path seeks `LipidBuilder`, however the extracted file is called `LipidBuilder_3.0`. I changed the folder name to `LipidBuilder`, but the same error comes up.

I have another plugin for VMD in the same plugin folder, and it works just fine.

FYI I am running this on a MacBook. I also tried running the same thing on Ubuntu, but the same problem comes up.

**Comment by tlemmin** [comment]
Did you download the plug-in from lipidbuidler.epfl.ch or github? 
Try getting the github one.

There is definitively a problem somewhere with your path.

**Comment by alkhalifas** [comment]
I downloaded the file from GitHub, and I still have the same error.

Let me ask you this: When editing the .vmdrc file, there is a lot of information already included in here. Where in the .vmdrc file should I place the script?

The .vmdrc file on my mac is empty, but the one on Linux is not. Here is a copy of the one on my mac:

`lappend auto_path /Users/username/plugins/vmd_density_profile-master`
   `menu main on`
`lappend auto_path /Users/username/plugins/LipidBuilder`
`vmd_install_extension lipidBuilder lipidbuilder_tk "Modeling/LipidBuild"`

**Comment by tlemmin** [comment]
Just add it at the end of the file.
Could you type these 3 commands in the tkConsole:
cd
lsearch -regexp -inline $auto_path ._LipidBuilder
ls [lsearch -regexp -inline $auto_path ._LipidBuilder]

The final output should be all the files in the LipidBuilder directory.

**Comment by alkhalifas** [comment]
Yup, I see a list of all of the files:

```
README.md*                          SLipid_hydrocarbon_topology.dat*
heads/                              heads.dat*
hydrocarbon_topology.dat*           hydrocarbon_topology_CHEMDRAW.dat*
lipidbuilder.tcl*                   minimize_Darwin*
minimize_Linux*                     parameters/
pkgIndex.tcl*                       smile2topology.tcl*
smiles_parser.tcl*                  topology/
topology_reader.tcl*                topology_writer.tcl*
writecharmmtop.tcl*                 zipper.tcl*
```

**Comment by tlemmin** [comment]
From tkConsole go into the Lipidbuilder folder.
cd [lsearch -regexp -inline $auto_path .LipidBuilder]
source lipidbuilder.tcl
lipidbuilder_tk

This should open LipidBuilder's GUI

**Comment by alkhalifas** [comment]
I was able to open the window successfully. I closed it and tried opening it from Extensions > Modeling > LipidBuilder, but that did not work.

I then tried to open it again the same way you mentioned above, and I received the following error message:
`>Main< (LipidBuilder) 24 % cd [lsearch -regexp -inline $auto_path .LipidBuilder]`
`>Main< (LipidBuilder) 25 % source lipidbuilder.tcl`
`>Main< (LipidBuilder) 26 % lipidbuilder_tk`
`can't set "category": can't set "headname": invalid command name ".lipidbuilder.sel1label"`

**Comment by tlemmin** [comment]
There is definitively a conflict somewhere. Since I cannot reproduce your error, it is hard to debug.
There is still an typo in you .vmdrc 
You should replace this line:
vmd_install_extension lipidBuilder lipidbuilder_tk "Modeling/LipidBuild"
with this line:
vmd_install_extension lipidbuilder lipidbuilder_tk "Modeling/LipidBuild"

**Comment by alkhalifas** [comment]
Hmm this is strange. I made the last change you suggested and I still receive the same error. I also gave this a try on my other computer and I ran into the same issue.

I also tried removing the software plugin completely and starting over.

**Comment by tlemmin** [comment]
I cannot reproduce your error. There is probably an error in the "vmd_install_extension" line.

Try running these command in the tkConsole:
lappend auto_path "your_path"/LipidBuilder
vmd_install_extension lipidbuilder lipidbuilder_tk "Modeling/LipidBuilder"

Then use the GUI to launch lipidbuilder.

**Comment by alkhalifas** [comment]
My apologies, I missed your message.

I just tried this command in the TK console:
`lappend auto_path "your_path"/LipidBuilder`

However, I received the following error:
`extra characters after close-quote`

So I tried to include the last portion as part of the quote:
lappend auto_path "/home/alkhalifas/Applications/vmd-1.9.3beta1/plugins/LipidBuilder_3.0/lipidbuilder.tcl"

Which gave me this:
`/usr/local/lib/vmd/scripts/tcl8.5 /usr/local/lib/vmd/scripts /usr/local/lib/lib /Projects/johns/tcl/8.5.6/lib_LINUXAMD64/lib /usr/local/lib/vmd/scripts/tk8.5 /usr/local/lib/vmd/scripts/tk8.5/ttk /usr/local/lib/vmd/scripts/vmd /usr/local/lib/vmd/plugins/LINUXAMD64/tcl /usr/local/lib/vmd/plugins/noarch/tcl /usr/local/lib/vmd/plugins/noarch/tcl/tablelist5.13/scripts {} /home/alkhalifas/Applications/vmd-1.9.3beta1/plugins/vmd_density_profile-master /home/alkhalifas/Applications/vmd-1.9.3beta1/plugins/LipidBuilder /home/alkhalifas/Applications/vmd-1.9.3beta1/plugins/LipidBuilder_3.0/lipidbuilder.tcl`

Upon adding the second command:
`vmd_install_extension lipidbuilder lipidbuilder_tk "Modeling/LipidBuilder"`

I received the following error:
`The lipidbuilder package could not be loaded:
Unable to add menu lipidbuilder`


I did however notice somthing new in the Terminal that I never saw before. I usually get the standard error message anytime I open vmd:
`vmd > ERROR) Creation of window for 'lipidbuilder' failed (invalid command name "lipidbuilder_tk").`

But this time it was followed by a new error:
`ERROR) Menu lipidbuilder already exists.`

**Comment by alkhalifas** [comment]
Hi there,

After weeks of failed attempts to get this plugin working, I tried it again today and it all works just fine! I am not sure what I did differently, or what the change was, if any. 

I just wanted to say thank you for all of the help you provided me!

**Comment by tlemmin** [comment]
Good to hear that!
